name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:
    runs-on: arc-runner-set
    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $(date +%s)
          
